name: Deploy release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/shared-public-configs/.github/workflows/publish-public-npm-package.yml@master
    with:
      build-script: >-
        graphql-codegen &&
        sed -i -e "s~\"version\": \"0.0.0-dev\"~\"version\": \"${GITHUB_REF##*/}\"~" package.json &&
        npm run build
      prepare-script: >-
        cp package.json LICENSE README.md build/ &&
        npm --prefix build pkg delete dependencies
