name: Deploy release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/shared-public-configs/.github/workflows/publish-public-npm-package.yml@master
    with:
      build-script: >-
        graphql-codegen &&
        tmp=$(mktemp) &&
        jq --arg version "$GITHUB_REF_NAME" '.version = $version' package.json > "$tmp" &&
        mv "$tmp" package.json &&
        npm run build
      prepare-script: >-
        cp package.json LICENSE README.md build/ &&
        npm --prefix build pkg delete dependencies devDependencies
