name: Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/github-workflows/.github/workflows/general/publish-npm-package.yml@unify-workflows
    with:
      node-version: "23"
      publish-access: "public"
      pre-build-script: >-
        npm run graphql-codegen &&
        sed -i -e "s~\"version\": \"0.0.0-dev\"~\"version\": \"${GITHUB_REF##*/}\"~" package.json
      prepare-script: >-
        cp package.json LICENSE README.md build/
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
